import {
  lightPrimaryColor,
  lightDangerColor,
  lightBackground,
  lightContent,
  lightHeaderText,
  lightInputBorder,
  lightLabel,
  lightButtonText,
  lightInputBackground,
  lightShadow,
  darkPrimaryColor,
  darkDangerColor,
  darkBackground,
  darkContent,
  darkHeaderText,
  darkInputBorder,
  darkLabel,
  darkButtonText,
  darkInputBackground,
  darkShadow,
} from './variables';

export const lightTheme = {
  primary: lightPrimaryColor,
  danger: lightDangerColor,
  body: lightBackground,
  form: lightContent,
  textHeader: lightHeaderText,
  border: lightInputBorder,
  label: lightLabel,
  buttonText: lightButtonText,
  inputBackground: lightInputBackground,
  shadow: lightShadow,
};

export const darkTheme = {
  primary: darkPrimaryColor,
  danger: darkDangerColor,
  body: darkBackground,
  form: darkContent,
  textHeader: darkHeaderText,
  border: darkInputBorder,
  label: darkLabel,
  buttonText: darkButtonText,
  inputBackground: darkInputBackground,
  shadow: darkShadow,
};
